spring:
  datasource:
    url: jdbc:mysql://localhost:3306/batch
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      dialect: org.hibernate.dialect.MySQLDialect
      show-sql: true
      format-sql: true
      ddl-auto: update
    show-sql: true


#debug: true